version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: swc_nginx

    app:
        build:
            context: .
            dockerfile: ./_docker/Dockerfile
        volumes:
            - ./:/var/www
        container_name: swc_app
    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        container_name: swc_mysql
